// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"backend/internal/models"
	"time"
)

type JobConnection struct {
	Items []*models.Job `json:"items"`
	Total int           `json:"total"`
}

type Mutation struct {
}

type PropertyConnection struct {
	Items []*models.Property `json:"items"`
	Total int                `json:"total"`
}

type PropertyInput struct {
	Price           int       `json:"price"`
	DateOfTransfer  time.Time `json:"dateOfTransfer"`
	Postcode        string    `json:"postcode"`
	PropertyType    string    `json:"propertyType"`
	OldNew          string    `json:"oldNew"`
	Duration        string    `json:"duration"`
	Paon            string    `json:"paon"`
	Saon            string    `json:"saon"`
	Street          string    `json:"street"`
	Locality        string    `json:"locality"`
	TownCity        string    `json:"townCity"`
	District        string    `json:"district"`
	County          string    `json:"county"`
	PpdCategoryType string    `json:"ppdCategoryType"`
	RecordStatus    string    `json:"recordStatus"`
}

type Query struct {
}
