package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"backend/internal/graph/model"
	"backend/internal/models"
	"context"
	"fmt"

	"github.com/google/uuid"
)

// Status is the resolver for the status field.
func (r *jobResolver) Status(ctx context.Context, obj *models.Job) (string, error) {
	return string(obj.Status), nil
}

// CreateProperty is the resolver for the createProperty field.
func (r *mutationResolver) CreateProperty(ctx context.Context, input model.PropertyInput) (*models.Property, error) {
	if !IsAdmin(ctx, r.Config) {
		return nil, fmt.Errorf("forbidden: admin access required")
	}
	prop := &models.Property{
		Price:           int64(input.Price),
		DateOfTransfer:  input.DateOfTransfer,
		Postcode:        input.Postcode,
		PropertyType:    input.PropertyType,
		OldNew:          input.OldNew,
		Duration:        input.Duration,
		PAON:            input.Paon,
		SAON:            input.Saon,
		Street:          input.Street,
		Locality:        input.Locality,
		TownCity:        input.TownCity,
		District:        input.District,
		County:          input.County,
		PPDCategoryType: input.PpdCategoryType,
		RecordStatus:    input.RecordStatus,
	}

	err := r.PropertyService.CreateProperty(ctx, prop)
	return prop, err
}

// UpdateProperty is the resolver for the updateProperty field.
func (r *mutationResolver) UpdateProperty(ctx context.Context, id string, input model.PropertyInput) (*models.Property, error) {
	if !IsAdmin(ctx, r.Config) {
		return nil, fmt.Errorf("forbidden: admin access required")
	}
	uid, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	prop := &models.Property{
		ID:              uid,
		Price:           int64(input.Price),
		DateOfTransfer:  input.DateOfTransfer,
		Postcode:        input.Postcode,
		PropertyType:    input.PropertyType,
		OldNew:          input.OldNew,
		Duration:        input.Duration,
		PAON:            input.Paon,
		SAON:            input.Saon,
		Street:          input.Street,
		Locality:        input.Locality,
		TownCity:        input.TownCity,
		District:        input.District,
		County:          input.County,
		PPDCategoryType: input.PpdCategoryType,
		RecordStatus:    input.RecordStatus,
	}

	err = r.PropertyService.UpdateProperty(ctx, prop)
	return prop, err
}

// DeleteProperty is the resolver for the deleteProperty field.
func (r *mutationResolver) DeleteProperty(ctx context.Context, id string) (bool, error) {
	if !IsAdmin(ctx, r.Config) {
		return false, fmt.Errorf("forbidden: admin access required")
	}
	err := r.PropertyService.DeleteProperty(ctx, id)
	return err == nil, err
}

// ID is the resolver for the id field.
func (r *propertyResolver) ID(ctx context.Context, obj *models.Property) (string, error) {
	return obj.ID.String(), nil
}

// Properties is the resolver for the properties field.
func (r *queryResolver) Properties(ctx context.Context, limit *int, offset *int, minPrice *int, maxPrice *int, postcode *string, townCity *string, county *string, propertyType *string) (*model.PropertyConnection, error) {
	var l int = 10
	if limit != nil {
		l = *limit
	}
	var o int = 0
	if offset != nil {
		o = *offset
	}

	filters := make(map[string]interface{})
	if minPrice != nil {
		filters["min_price"] = *minPrice
	}
	if maxPrice != nil {
		filters["max_price"] = *maxPrice
	}
	if postcode != nil {
		filters["postcode"] = *postcode
	}
	if townCity != nil {
		filters["town_city"] = *townCity
	}
	if county != nil {
		filters["county"] = *county
	}
	if propertyType != nil {
		filters["property_type"] = *propertyType
	}

	props, count, err := r.PropertyService.GetProperties(ctx, filters, l, o)
	if err != nil {
		return nil, err
	}

	items := make([]*models.Property, len(props))
	for i := range props {
		items[i] = &props[i]
	}
	return &model.PropertyConnection{
		Items: items,
		Total: int(count),
	}, nil
}

// Property is the resolver for the property field.
func (r *queryResolver) Property(ctx context.Context, id string) (*models.Property, error) {
	return r.PropertyService.GetPropertyByID(ctx, id)
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context, limit *int, offset *int) (*model.JobConnection, error) {
	var l int = 10
	if limit != nil {
		l = *limit
	}
	var o int = 0
	if offset != nil {
		o = *offset
	}

	jobs, count, err := r.JobService.GetJobs(ctx, l, o)
	if err != nil {
		return nil, err
	}

	items := make([]*models.Job, len(jobs))
	for i := range jobs {
		items[i] = &jobs[i]
	}

	return &model.JobConnection{
		Items: items,
		Total: int(count),
	}, nil
}

// Job returns JobResolver implementation.
func (r *Resolver) Job() JobResolver { return &jobResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Property returns PropertyResolver implementation.
func (r *Resolver) Property() PropertyResolver { return &propertyResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type jobResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type propertyResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
