// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/migrate-existing": {
            "post": {
                "security": [
                    {
                        "JwtAuth": []
                    }
                ],
                "description": "Queue a migration job for a file already in the bucket",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Trigger migration for existing bucket file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key in bucket",
                        "name": "bucketKey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "CSV has header",
                        "name": "hasHeader",
                        "in": "query"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.JobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Admin only)",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/reset": {
            "post": {
                "security": [
                    {
                        "JwtAuth": []
                    }
                ],
                "description": "Truncate properties and jobs tables, clear queues, and clear analytics cache",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Reset backend state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.BaseResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Admin only)",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/stream-upload": {
            "post": {
                "security": [
                    {
                        "JwtAuth": []
                    }
                ],
                "description": "Stream a large CSV file directly from the request body to bucket and queue a migration job",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Stream upload CSV file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Original filename",
                        "name": "filename",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.JobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Admin only)",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/upload": {
            "post": {
                "security": [
                    {
                        "JwtAuth": []
                    }
                ],
                "description": "Upload a CSV file via multipart/form-data to bucket and queue a migration job",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Upload CSV file directly",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.JobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Admin only)",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "JwtAuth": []
                    }
                ],
                "description": "Get a list of all users. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/backend_internal_models.User"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JwtAuth": []
                    }
                ],
                "description": "Create a new user with specified role. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}": {
            "put": {
                "security": [
                    {
                        "JwtAuth": []
                    }
                ],
                "description": "Update user details. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JwtAuth": []
                    }
                ],
                "description": "Delete a user by ID. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/affordability": {
            "get": {
                "description": "Get relative affordability by property type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get affordability index",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.AffordabilityResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/growth-hotspots": {
            "get": {
                "description": "Get regions with highest price growth rate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get growth hotspots",
                "parameters": [
                    {
                        "type": "string",
                        "default": "district",
                        "description": "Region type (county, district, town_city)",
                        "name": "by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of results (0 for all)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Year to filter by",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.GrowthHotspotResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/median-price": {
            "get": {
                "description": "Get median price grouped by county, district, or town_city",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get median price by region",
                "parameters": [
                    {
                        "type": "string",
                        "default": "county",
                        "description": "Region type (county, district, town_city)",
                        "name": "by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Year to filter by",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.MedianPriceResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/new-build-premium": {
            "get": {
                "description": "Get average prices of new builds vs established properties by region",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get new build premium",
                "parameters": [
                    {
                        "type": "string",
                        "default": "county",
                        "description": "Region type (county, district, town_city)",
                        "name": "by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.NewBuildPremiumResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/price-bracket-distribution": {
            "get": {
                "description": "Get distribution of properties by price ranges",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get price bracket distribution",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.PriceBracketResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/price-trend": {
            "get": {
                "description": "Get average and median price trends over time",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get price trend analysis",
                "parameters": [
                    {
                        "type": "string",
                        "default": "month",
                        "description": "Time interval (month, year)",
                        "name": "interval",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.PriceTrendResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/property-type-distribution": {
            "get": {
                "description": "Get distribution of properties by type (detached, semi, flat, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get property type distribution",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.PropertyTypeDistributionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/time-range": {
            "get": {
                "description": "Get minimum and maximum year available in the dataset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get available time range for analytics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.TimeRangeResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analytics/top-active-areas": {
            "get": {
                "description": "Get regions with highest transaction volume",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get top active areas",
                "parameters": [
                    {
                        "type": "string",
                        "default": "district",
                        "description": "Region type (county, district, town_city)",
                        "name": "by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Year to filter by",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.TopActiveAreaResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/query": {
            "post": {
                "description": "Execute complex queries and mutations for properties and background jobs.\n\nThis endpoint provides a flexible way to fetch exactly the data you need.\nIt supports filtering, pagination, and nested data structures.\n\n### Authentication\nThis endpoint uses Optional JWT Authentication.\n- Public users can query property listings.\n- Authenticated users can access additional details.\n- Admin users (identified by JWT) can perform mutations like creating, updating, or deleting properties.\n\n### Example Property Query\n` + "`" + `` + "`" + `` + "`" + `graphql\nquery {\nproperties(limit: 10, minPrice: 200000, townCity: \"London\") {\nitems {\nid\nprice\nstreet\npostcode\n}\ntotal\n}\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n### Example Job Query (Admin only)\n` + "`" + `` + "`" + `` + "`" + `graphql\nquery {\njobs(limit: 5) {\nitems {\nid\nstatus\nprogress\ntaskType\n}\ntotal\n}\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n### Example Mutations (Admin only)\n\n**Create Property:**\n` + "`" + `` + "`" + `` + "`" + `graphql\nmutation {\ncreateProperty(input: {\nprice: 250000,\ndateOfTransfer: \"2024-03-07T00:00:00Z\",\npostcode: \"SW1A 1AA\",\npropertyType: \"D\",\noldNew: \"N\",\nduration: \"F\",\npaon: \"10\",\nsaon: \"\",\nstreet: \"Downing Street\",\nlocality: \"Westminster\",\ntownCity: \"London\",\ndistrict: \"Greater London\",\ncounty: \"London\",\nppdCategoryType: \"A\",\nrecordStatus: \"A\"\n}) { id price street }\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n**Update Property:**\n` + "`" + `` + "`" + `` + "`" + `graphql\nmutation {\nupdateProperty(id: \"UUID-HERE\", input: {\nprice: 260000,\n# ... other fields\n}) { id price }\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n**Delete Property:**\n` + "`" + `` + "`" + `` + "`" + `graphql\nmutation {\ndeleteProperty(id: \"UUID-HERE\")\n}\n` + "`" + `` + "`" + `` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GraphQL"
                ],
                "summary": "Unified GraphQL API",
                "parameters": [
                    {
                        "description": "GraphQL Operation (Query or Mutation)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.GraphQLRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.GraphQLResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid GraphQL request",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized (if authentication is required for specific operation)",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate a user with username and password. Returns a JWT token and user info, and sets HTTP-only cookies for session management.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.LoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid username or password",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Log out the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.BaseResponse"
                        }
                    }
                }
            }
        },
        "/user/change-password": {
            "post": {
                "security": [
                    {
                        "JwtAuth": []
                    }
                ],
                "description": "Change the password of the currently logged-in user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Change own password",
                "parameters": [
                    {
                        "description": "Password details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_routes_api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "backend_internal_models.AffordabilityResult": {
            "type": "object",
            "properties": {
                "avg_price": {
                    "type": "integer"
                },
                "property_type": {
                    "type": "string"
                },
                "relative_affordability": {
                    "type": "number"
                }
            }
        },
        "backend_internal_models.GrowthHotspotResult": {
            "type": "object",
            "properties": {
                "current_median": {
                    "type": "integer"
                },
                "growth_rate": {
                    "type": "number"
                },
                "prev_median": {
                    "type": "integer"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "backend_internal_models.MedianPriceResult": {
            "type": "object",
            "properties": {
                "median_price": {
                    "type": "integer"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "backend_internal_models.NewBuildPremiumResult": {
            "type": "object",
            "properties": {
                "new_avg": {
                    "type": "integer"
                },
                "old_avg": {
                    "type": "integer"
                },
                "premium_percent": {
                    "type": "number"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "backend_internal_models.PriceBracketResult": {
            "type": "object",
            "properties": {
                "bracket": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                }
            }
        },
        "backend_internal_models.PriceTrendResult": {
            "type": "object",
            "properties": {
                "avg_price": {
                    "type": "integer"
                },
                "median_price": {
                    "type": "integer"
                },
                "period": {
                    "type": "string"
                },
                "transaction_count": {
                    "type": "integer"
                }
            }
        },
        "backend_internal_models.PropertyTypeDistributionResult": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                },
                "property_type": {
                    "type": "string"
                }
            }
        },
        "backend_internal_models.TimeRangeResult": {
            "type": "object",
            "properties": {
                "max_year": {
                    "type": "integer"
                },
                "min_year": {
                    "type": "integer"
                }
            }
        },
        "backend_internal_models.TopActiveAreaResult": {
            "type": "object",
            "properties": {
                "region": {
                    "type": "string"
                },
                "total_value": {
                    "type": "integer"
                },
                "transaction_count": {
                    "type": "integer"
                }
            }
        },
        "backend_internal_models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "type": "integer"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "refresh_version": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_routes_api.AffordabilityResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_models.AffordabilityResult"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.BaseResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 6
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "internal_routes_api.CreateUserRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "is_admin": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_routes_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_routes_api.GraphQLError": {
            "type": "object",
            "properties": {
                "extensions": {
                    "type": "object",
                    "additionalProperties": true
                },
                "locations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_routes_api.GraphQLLocation"
                    }
                },
                "message": {
                    "type": "string"
                },
                "path": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "internal_routes_api.GraphQLLocation": {
            "type": "object",
            "properties": {
                "column": {
                    "type": "integer"
                },
                "line": {
                    "type": "integer"
                }
            }
        },
        "internal_routes_api.GraphQLRequest": {
            "type": "object",
            "properties": {
                "operationName": {
                    "description": "Optional operation name if multiple are defined in the query",
                    "type": "string"
                },
                "query": {
                    "description": "The GraphQL query or mutation string",
                    "type": "string",
                    "example": "query { properties(limit: 5) { items { id price street } } }"
                },
                "variables": {
                    "description": "Optional variables for the operation",
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "internal_routes_api.GraphQLResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "The requested data"
                },
                "errors": {
                    "description": "Any errors encountered during execution",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_routes_api.GraphQLError"
                    }
                }
            }
        },
        "internal_routes_api.GrowthHotspotResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_models.GrowthHotspotResult"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.JobResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.LoginBody": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_routes_api.LoginResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean",
                    "example": true
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/backend_internal_models.User"
                }
            }
        },
        "internal_routes_api.MedianPriceResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_models.MedianPriceResult"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.NewBuildPremiumResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_models.NewBuildPremiumResult"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.PriceBracketResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_models.PriceBracketResult"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.PriceTrendResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_models.PriceTrendResult"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.PropertyTypeDistributionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_models.PropertyTypeDistributionResult"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.TimeRangeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/backend_internal_models.TimeRangeResult"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.TopActiveAreaResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend_internal_models.TopActiveAreaResult"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_routes_api.UpdateUserRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "is_admin": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JwtAuth": {
            "description": "Type 'Bearer ' followed by your JWT token in the input field. The token can be obtained from the /auth/login endpoint.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "UK Housing Market & Rental Intelligence API",
	Description:      "This is a comprehensive API for analyzing and accessing UK housing market and rental data.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
